import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./component/common/header";
import Footer from "./component/common/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "back2basics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />

        {children}
        <Footer />
      </body>
    </html>
  );
}
